version: 2.1

executors:
  go-executor:
    docker:
      - image: cimg/go:1.24

jobs:
  build:
    executor: go-executor

    steps:
      - checkout

      - run:
          name: "Verify Go version"
          command: go version

      - run:
          name: "Install dependencies"
          command: go mod tidy

      - run:
          name: "Run Tests with Coverage"
          command: |
            go test -v -covermode=count -coverprofile=coverage.out -tags exclude_test ./...

      - store_artifacts:
          path: coverage.out

      - store_test_results:
          path: tests

      - run:
          name: "Upload Coverage to Coveralls"
          command: |
            go install github.com/mattn/goveralls@latest
            if [ -z "$COVERALLS_TOKEN" ]; then 
              echo "COVERALLS_TOKEN is missing! Skipping upload.";
            else
              goveralls -coverprofile=coverage.out -service=circleci -repotoken $COVERALLS_TOKEN
            fi

workflows:
  version: 2.1
  build_and_test:
    jobs:
      - build:
          filters:
            branches:
              only: main